// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ExpandBtn: typeof import('./src/components/common/expand-btn.vue')['default']
    Footer: typeof import('./src/components/footer.vue')['default']
    LegendBtn: typeof import('./src/components/common/legend-btn.vue')['default']
    Loading: typeof import('element-plus/es')['ElLoadingDirective']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Slice: typeof import('./src/components/common/slice.vue')['default']
    SyncBtn: typeof import('./src/components/common/sync-btn.vue')['default']
    XBar: typeof import('./src/components/charts/x-bar.vue')['default']
    XChart: typeof import('./src/components/charts/x-chart.vue')['default']
    XCircle: typeof import('./src/components/charts/x-circle.vue')['default']
    XHbar: typeof import('./src/components/charts/x-hbar.vue')['default']
    XLine: typeof import('./src/components/charts/x-line.vue')['default']
    XLineArea: typeof import('./src/components/charts/x-line-area.vue')['default']
    XNumber: typeof import('./src/components/charts/x-number.vue')['default']
    XPie: typeof import('./src/components/charts/x-pie.vue')['default']
  }
}

export {}
